local c = require("colors.utils").colors
local s = require("colors.utils").styles
local Group = require("colors.utils").Group

-- see :help cmp-highlight
Group.new("CmpPmenu", nil, c.black:dark(0.03))
Group.new("CmpBorder", c.grey)
Group.new("CmpDocBorder", c.black:dark(0.03), c.black:dark(0.03))
Group.new("CmpItemAbbr", c.white)
Group.new("CmpItemAbbrMatch", c.blue, nil, s.bold)
Group.new("CmpItemKindConstant", c.base09)
Group.new("CmpItemKindFunction", c.base0D)
Group.new("CmpItemKindIdentifier", c.base08)
Group.new("CmpItemKindField", c.base08)
Group.new("CmpItemKindVariable", c.base0E)
Group.new("CmpItemKindSnippet", c.red)
Group.new("CmpItemKindText", c.base0B)
Group.new("CmpItemKindStructure", c.base0E)
Group.new("CmpItemKindType", c.base0A)
Group.new("CmpItemKindKeyword", c.base0E)
Group.new("CmpItemKindMethod", c.base0D)
Group.new("CmpItemKindConstructor", c.blue)
Group.new("CmpItemKindFolder", c.base07)
Group.new("CmpItemKindModule", c.base0A)
Group.new("CmpItemKindProperty", c.base08)
Group.new("CmpItemKindUnit", c.base0E)
Group.new("CmpItemKindFile", c.base07)
Group.new("CmpItemKindColor", c.red)
Group.new("CmpItemKindReference", c.base05)
Group.new("CmpItemKindStruct", c.base0E)
Group.new("CmpItemKindOperator", c.base05)
Group.new("CmpItemKindTypeParameter", c.base08)
Group.new("CmpItemKindCopilot", c.green)
