local c = require("colors.utils").colors
local Group = require("colors.utils").Group

Group.new("DiffAdd", nil, c.diff_add)
Group.new("DiffChange", nil, c.diff_change)
Group.new("DiffDelete", nil, c.diff_delete)
Group.new("DiffText", nil, c.diff_text)
Group.new("DiffAdded", c.green)
Group.new("DiffChangeDelete", c.red)
Group.new("DiffModified", c.yellow)
Group.new("DiffRemoved", c.red)
Group.new("DiffFile", c.cyan)
Group.new("DiffIndexLine", c.grey)
Group.new("diffAdded", c.green)
Group.new("diffRemoved", c.red)
Group.new("diffChanged", c.yellow)
Group.new("diffOldFile", c.orange)
Group.new("diffNewFile", c.green)
Group.new("diffFile", c.cyan)
Group.new("diffLine", c.black)
Group.new("diffIndexLine", c.grey)
