local c = require("colors.utils").colors
local s = require("colors.utils").styles
local Group = require("colors.utils").Group

Group.new("NeoTreeBufferNumber", c.pink)
Group.new("NeoTreeDimText", c.grey)
Group.new("NeoTreeDirectoryIcon", c.folder_bg)
Group.new("NeoTreeDirectoryName", c.folder_bg)
Group.new("NeoTreeDotfile", c.grey)
Group.new("NeoTreeExpander", c.yellow)
Group.new("NeoTreeFileName", c.white)
Group.new("NeoTreeFileNameOpened", c.yellow)
Group.new("NeoTreeFilterTerm", c.purple)
Group.new("NeoTreeFloatBorder", c.blue)
Group.new("NeoTreeFloatTitle", c.white, nil, s.bold)
Group.new("NeoTreeGitAdded", c.green)
Group.new("NeoTreeGitConflict", c.red)
Group.new("NeoTreeGitDeleted", c.red)
Group.new("NeoTreeGitIgnored", c.grey)
Group.new("NeoTreeGitModified", c.orange)
Group.new("NeoTreeGitStaged", c.cyan)
Group.new("NeoTreeGitUnstaged", c.purple)
Group.new("NeoTreeGitUntracked", c.yellow)
Group.new("NeoTreeIndentMarker", c.grey)
Group.new("NeoTreeNormal", c.white)
Group.new("NeoTreeNormalNC", c.white)
Group.new("NeoTreeRootName", c.white, nil, s.bold)
Group.new("NeoTreeSymbolicLinkTarget", c.cyan)
Group.new("NeoTreeTitleBar", c.blue, c.black)
Group.new("NeoTreeUntracked", c.yellow)
