return {
  {
    "nvim-treesitter/nvim-treesitter",
    run = ":TSUpdate",
    config = function()
      require("config.plugin.treesitter.setup")
    end,
    module = "nvim-treesitter",
    ft = {
      "bash",
      "bib",
      "c",
      "cpp",
      "cs",
      "css",
      "dart",
      "dockerfile",
      "fish",
      "go",
      "gomod",
      "graphql",
      "html",
      "java",
      "javascript",
      "javascriptreact",
      "json",
      "jsonc",
      "lua",
      "make",
      "markdown",
      "php",
      "python",
      "ruby",
      "rust",
      "scss",
      "sh",
      "svelte",
      "tex",
      "toml",
      "typescript",
      "typescriptreact",
      "vim",
      "vlang",
      "vue",
      "yaml",
      "zig",
    },
  },
  {
    "nvim-treesitter/nvim-treesitter-refactor",
    after = "nvim-treesitter",
  },
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
    after = "nvim-treesitter",
  },
  {
    "JoosepAlviste/nvim-ts-context-commentstring",
    after = "nvim-treesitter",
  },
  {
    "windwp/nvim-ts-autotag",
    after = "nvim-treesitter",
  },
}
