local c = require("colors.utils").colors
local g = require("colors.utils").groups
local s = require("colors.utils").styles
local Group = require("colors.utils").Group

-- builtins
-- see :help highlight-groups
Group.new("ColorColumn", nil, c.cursor_grey)
Group.new("Conceal", c.base01)
Group.new("Cursor", c.black, c.blue)
Group.new("CursorIM", c.base05, c.base00)
Group.new("CursorColumn", nil, c.cursor_grey)
if vim.wo.diff then
  Group.new("CursorLine", nil, nil, s.underline) -- Don't change the background color in diff mode
else
  Group.new("CursorLine", nil, c.cursor_grey)
end
Group.new("Directory", c.blue)
Group.new("EndOfBuffer", c.black)
Group.new("TermCursor", c.base05, c.base00)
Group.new("TermCursorNC", c.base05, c.base00)
Group.new("ErrorMsg", c.base08)
Group.new("WinSeparator", c.black:light(0.15))
Group.new("Folded", c.comment_grey)
Group.new("SignColumn", c.base03)
Group.new("IncSearch", c.yellow, c.comment_grey)
Group.new("Substitute", c.base01, c.base0A)
Group.new("LineNr", c.grey)
Group.new("CursorLineNr", c.white)
Group.new("MatchParen", c.white, c.grey, s.bold)
Group.new("ModeMsg", c.base0B, nil, s.bold)
Group.new("ModeArea", c.white, nil, s.bold)
Group.new("MsgSeparator", c.purple:light(), nil, s.bold)
Group.new("MoreMsg", c.blue:light())
Group.new("NonText", c.base03)
Group.new("Normal", c.base05, c.base00)
Group.new("NormalFloat", nil, c.black:dark(0.06))
Group.new("NormalNC", c.white, c.base00)
Group.new("FloatBorder", c.blue)
Group.new("PMenu", c.white, c.menu_grey)
Group.new("PMenuSel", c.cursor_grey, c.pmenu_bg)
Group.new("PMenuSBar", nil, c.cursor_grey)
Group.new("PMenuThumb", nil, c.white)
Group.new("Question", c.purple)
Group.new("QuickFixLine", c.black, c.yellow)
Group.new("Search", c.base01, c.base0A)
Group.new("SpecialKey", c.special_grey)
Group.new("SpellBad", c.base08, nil, s.underline)
Group.new("SpellLocal", c.dark_yellow)
Group.new("SpellCap", c.dark_yellow)
Group.new("SpellRare", c.dark_yellow)
Group.new("StatusLine", c.white, c.statusline_bg)
Group.new("StatusLineNC", c.comment_grey)
Group.new("StatusLineTerm", c.white, c.statusline_bg)
Group.new("StatusLineTermNC", c.comment_grey)
Group.new("TabLine", c.comment_grey)
Group.new("TabLineFill", g.Tabline, g.Tabline, g.Tabline)
Group.new("TabLineSel", c.white)
Group.new("Title", c.green)
Group.new("Visual", nil, c.visual_grey)
Group.new("VisualNOS", nil, c.visual_grey)
Group.new("WarningMsg", c.yellow)
Group.new("Whitespace", c.grey:dark())
Group.new("WildMenu", c.black, c.blue)
Group.new("WinBar", c.yellow)
Group.new("WinBarNC", c.grey)

-- others
Group.new("MatchWord", g.MatchParen, g.MatchParen, g.MatchParen)
Group.new("VertSplit", c.line, nil, nil)
Group.new("Warnings", c.yellow:light(), nil, nil)
Group.new("healthError", c.red:light(), nil, nil)
Group.new("healthSuccess", c.green:light(), nil, nil)
Group.new("healthWarning", c.yellow:light(), nil, nil)
Group.new("qfLineNr", c.grey, nil, s.reverse)
Group.new("TooLong", c.base08)
