local c = require("colors.utils").colors
local g = require("colors.utils").groups
local s = require("colors.utils").styles
local Group = require("colors.utils").Group

-- builtins
-- see :help highlight-groups
Group.new("ColorColumn", nil, c.base01, s.NONE)
Group.new("Conceal", c.base01, nil, nil)
Group.new("Cursor", c.base05, c.base00, nil)
Group.new("CursorIM", c.base05, c.base00, nil)
Group.new("CursorColumn", nil, c.base01, s.NONE)
Group.new("CursorLine", nil, c.base00:light(0.05), nil)
Group.new("Directory", c.blue, nil, nil)
Group.new("EndOfBuffer", c.base05, nil, nil)
Group.new("TermCursor", c.base05, c.base00, nil)
Group.new("TermCursorNC", c.base05, c.base00, nil)
Group.new("ErrorMsg", c.base08, c.base00, nil)
Group.new("WinSeparator", c.black:light(0.15), nil, nil)
Group.new("Folded", c.base03, c.base01, nil)
Group.new("FoldColumn", c.base0C, c.base01, nil)
Group.new("SignColumn", c.base03, nil, s.NONE)
Group.new("IncSearch", c.base01, c.base09, s.NONE)
Group.new("Substitute", c.base01, c.base0A, s.NONE)
Group.new("LineNr", c.grey)
Group.new("CursorLineNr", c.white)
Group.new("MatchParen", c.white, c.grey, s.bold)
Group.new("ModeMsg", c.base0B, nil, s.bold)
Group.new("ModeArea", c.white, nil, s.bold)
Group.new("MsgSeparator", c.purple:light(), nil, s.bold)
Group.new("MoreMsg", c.blue:light(), nil, nil)
Group.new("NonText", c.base03, nil, nil)
Group.new("Normal", c.base05, c.base00, nil)
Group.new("NormalFloat", nil, c.black:dark(0.06), nil)
Group.new("NormalNC", c.white, c.base00, nil)
Group.new("FloatBorder", c.blue, nil, nil)
Group.new("PMenu", nil, c.black:light(), nil)
Group.new("PMenuSel", c.black, c.pmenu_bg, nil)
Group.new("PMenuSBar", nil, c.black:light(), nil)
Group.new("PMenuThumb", nil, c.grey, nil)
Group.new("Question", c.base0D, nil, nil)
Group.new("QuickFixLine", c.base04, c.base01, nil)
Group.new("Search", c.base01, c.base0A, s.NONE)
Group.new("SpecialKey", c.base03, nil, nil)
Group.new("SpellBad", c.base08, nil, s.underline)
Group.new("SpellLocal", c.base0C, nil, s.underline)
Group.new("SpellCap", c.base0D, nil, s.underline)
Group.new("SpellRare", c.base0E, nil, s.underline)
Group.new("StatusLine", nil, c.statusline_bg, nil)
Group.new("StatusLineNC", c.base03, c.statusline_bg, nil)
Group.new("TabLine", g.StatusLineNC, g.StatusLineNC, g.StatusLineNC)
Group.new("TabLineFill", g.Tabline, g.Tabline, g.Tabline)
Group.new("TabLineSel", g.Normal, g.Normal, g.Normal)
Group.new("Title", c.green:dark(), nil, s.bold)
Group.new("Visual", nil, c.base02, nil)
Group.new("VisualNOS", c.base08, nil, nil)
Group.new("WarningMsg", c.yellow:light(), nil, nil)
Group.new("Whitespace", c.grey:dark(), nil, nil)
Group.new("WildMenu", c.base08, c.base0A, nil)
Group.new("WinBar", c.yellow, nil, nil)
Group.new("WinBarNC", c.grey, nil, nil)

-- others
Group.new("MatchWord", g.MatchParen, g.MatchParen, g.MatchParen)
Group.new("InsertMode", c.black, c.blue:dark(), nil)
Group.new("NormalMode", c.black, c.yellow, nil)
Group.new("ReplacelMode", c.black, c.pink:dark(), nil)
Group.new("VisualMode", c.black, c.pink:dark(), nil)
Group.new("VertSplit", c.line, nil, nil)
Group.new("Warnings", c.yellow:light(), nil, nil)
Group.new("healthError", c.red:light(), nil, nil)
Group.new("healthSuccess", c.green:light(), nil, nil)
Group.new("healthWarning", c.yellow:light(), nil, nil)
Group.new("qfLineNr", c.grey, nil, s.reverse)
Group.new("TooLong", c.base08)
