local c = require("colors.utils").colors
local s = require("colors.utils").styles
local Group = require("colors.utils").Group

Group.new("Type", c.base0A)
Group.new("Typedef", c.base0A)
Group.new("StorageClass", c.base0A)
Group.new("Keyword", c.base0E)
Group.new("Structure", c.base0A)
Group.new("Comment", c.comment_grey)
Group.new("Conditional", c.base0E)
Group.new("Constant", c.cyan)
Group.new("Character", c.base0B)
Group.new("Number", c.base09)
Group.new("Boolean", c.base09)
Group.new("Float", c.base09)
Group.new("Function", c.base0D)
Group.new("Method", c.base0D)
Group.new("Identifier", c.base08)
Group.new("Statement", c.base0E)
Group.new("Label", c.base0E)
Group.new("Operator", c.purple) -- sizeof, +, *, etc...
Group.new("Exception", c.purple) -- try, catch, throw
Group.new("PreProc", c.base0A)
Group.new("Include", c.base0D)
Group.new("Define", c.base0E)
Group.new("Macro", c.base0E)
Group.new("PreCondit", c.base0A)
Group.new("Repeat", c.base0E) -- for, do, while, etc...
Group.new("String", c.base0B)
Group.new("Special", c.base0D)
Group.new("SpecialChar", c.dark_yellow)
Group.new("Tag", c.blue:light())
Group.new("Delimiter", c.blue:dark())
Group.new("SpecialComment", c.comment_grey)
Group.new("Debug", c.base08)
Group.new("Underlined", c.base0B, nil, s.underline)
Group.new("Ignore", c.grey)
Group.new("Error", c.base08)
Group.new("Todo", c.base0E)
