local c = require("colors.utils").colors
local g = require("colors.utils").groups
local s = require("colors.utils").styles
local Group = require("colors.utils").Group

Group.new("Type", c.base0A)
Group.new("Typedef", c.base0A)
Group.new("StorageClass", c.base0A)
Group.new("Keyword", c.base0E)
Group.new("Structure", g.Keyword.fg)
Group.new("Comment", c.base03)
Group.new("Conditional", c.base0E)
Group.new("Constant", c.base08)
Group.new("Character", c.base08)
Group.new("Number", c.base09)
Group.new("Boolean", c.base09, nil, s.bold)
Group.new("Float", c.base09)
Group.new("Function", c.base0D)
Group.new("Method", c.base0D)
Group.new("Identifier", c.base08)
Group.new("Statement", c.base08)
Group.new("Label", c.base0A)
Group.new("Operator", c.base05)
Group.new("Exception", c.base08)
Group.new("PreProc", c.base0A)
Group.new("Include", c.base0D)
Group.new("Define", c.base0E)
Group.new("Macro", c.base08)
Group.new("PreCondit", c.base0A)
Group.new("Repeat", c.pink:dark())
Group.new("String", c.base0B)
Group.new("Special", c.base0C)
Group.new("SpecialChar", c.pink:dark())
Group.new("Tag", c.blue:light())
Group.new("Delimiter", c.blue:dark())
Group.new("SpecialComment", c.green:light(), nil, s.bold)
Group.new("Debug", c.base08)
Group.new("Underlined", c.base0B, nil, s.underline)
Group.new("Ignore", c.grey)
Group.new("Error", c.base00, c.base08, nil)
Group.new("Todo", c.base0A, c.base01, nil)
