require("colors.highlights.syntax.general")
require("colors.highlights.syntax.lua")
require("colors.highlights.syntax.json")
require("colors.highlights.syntax.markdown")
require("colors.highlights.syntax.ruby")
