local c = require("colors.utils").colors
local g = require("colors.utils").groups
local s = require("colors.utils").styles
local Group = require("colors.utils").Group

Group.new("luaBuiltIn", g.Keyword)
Group.new("luaDocTag", c.green, nil, s.bold)
Group.new("luaFunc", g.Identifier)
Group.new("luaFunction", g.Function)
Group.new("luaFuncTable", g.Function)
Group.new("luaIn", g.Keyword)
Group.new("luaCond", g.Conditional)
Group.new("luaCondElse", g.Conditional)
Group.new("luaCondEnd", g.Conditional)
Group.new("luaParen", g.Delimiter)
Group.new("luaParens", g.Delimiter)
Group.new("luaBraces", g.Delimiter)
Group.new("luaBracket", g.Delimiter)
Group.new("luaBrackets", g.Delimiter)
Group.new("luaIfThen", g.Conditional)
Group.new("luaElse", g.Conditional)
Group.new("luaSpecialTable", c.yellow:light(), nil, s.bold)
Group.new("luaFuncParen", c.purple:light())
Group.new("luaFuncParens", g.luaFuncParen)
Group.new("luaFuncArgName", c.cyan:light())
Group.new("luaTable", c.red:light())
Group.new("luaSpecial", c.cyan:dark(), nil, s.bold)
Group.new("luaEllipsis", c.red:dark(), nil, s.bold)
Group.new("luaStatement", g.Statement)
Group.new("luaRepeat", g.Repeat)
Group.new("luaFor", g.Repeat)
Group.new("luaString", g.String)
Group.new("luaString2", g.String)
Group.new("luaStringDelimiter", g.luaString)
Group.new("luaNumber", g.Number)
Group.new("luaOperator", g.Operator)
Group.new("luaSymbolOperator", g.luaOperator)
Group.new("luaConstant", g.Constant)
Group.new("luaMetaMethod", g.Method)
Group.new("luaComment", g.Comment)
Group.new("luaCommentDelimiter", g.luaComment)
Group.new("luaTodo", g.Todo)
Group.new("luaError", g.Error)
Group.new("luaParenError", g.Error)
Group.new("luaLabel", g.Label)
Group.new("luaKeyword", c.orange:dark(), nil, s.bold)
Group.new("luaMyKeyword", c.purple:light(), nil, s.bold)
Group.new("luaFunctionCall", c.blue:dark())
Group.new("luaSpecialFunctions", c.blue:light())
Group.new("luaMetatableEvents", c.purple)
Group.new("luaMetatableArithmetic", g.luaMetatableEvents)
Group.new("luaMetatableEquivalence", g.luaMetatableEvents)
